media:
  - name: images
    label: images
    input: src/assets
    output: src/assets
  - name: icons
    label: icons
    input: src/icons
    output: src/icons
    
content:
  - name: site_page
    label: Pages
    path: src/content/site_page
    type: collection
    fields:
      - name: title
        label: Title
        type: text
        required: true
      - name: description
        label: Description
        type: text
      - name: heroImage
        label: Image
        type: text
      - name: body
        type: rich-text
        required: true

  - name: blog
    label: Blog
    path: src/content/blog
    type: collection
    fields: 
      - name: title
        label: Title
        type: text
        required: true
      - name: description
        label: Description
        type: text
      - name: pubDate
        label: Date
        type: date
      - name: heroImage
        label: Image
        type: text
      - name: body
        type: rich-text
        required: true
  - name: hero
    label: Homepage
    path: src/content/home.md
    type: file
    fields:
      - name: title
        label: Title
        type: text
        required: true
      - name: description
        label: description
        type: text
      - name: cta
        label: Call to Action
        type: text
        required: true
      - name: cta_link
        label: Call to Action Link
        type: text
        required: true
    